builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archive:
  format: tar.gz

checksum:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_checksums.txt"
